### ISSUE TITLE
Add an example to the Readme

### ISSUE THREAD

**Issue by nitnelave** [clayrisser/react-ast#1]
Hi,

The readme would really benefit from a visual example, especially for a visualization library. Otherwise, it's hard to evaluate the quality of the library:

- If the visual is bad, the library is useless,
- If the visual is good, it makes me want to use the library!

**Comment by clayrisser** [comment]
Hmmm, the README.md already has an example. Could you direct me in how to improve it? Could you clarify what you mean by "visual" example?

**Comment by nitnelave** [comment]
Hmmm, then I was mislead by the title: I feel that "render" is usually associated with creating an image from a specification, so I expected a visual representation of the AST (maybe graphviz or something like that). But you render the AST to text, which is a bit confusing.

I don't have a clear improvement in mind, but on a quick glance, the readme is a bit confusing.

**Comment by clayrisser** [comment]
No it actually renders AST and optionally renders the rendered AST to text. Look at the second example.

**Comment by nitnelave** [comment]
Your second example doesn't have an image, I don't see what it does:
![render_ast](https://user-images.githubusercontent.com/796633/63955290-c1f40780-ca84-11e9-93e4-b5c641060fe6.png)

**Comment by clayrisser** [comment]
No, there should be an AST tree there. I can paste an example but it would be huge. Maybe I'll put a small sample of the data it renders.

It's not a renderer that renders a UI. It renders an AST tree and optionally text from the AST tree. It's a bit confusing because it's a brand new concept. A concept that's only 12 hours old :laughing:

It is however by definition a true react renderer.

**Comment by nitnelave** [comment]
I think a screenshot here would be very helpful, it's hard to grasp your 12h-old concept from just this text description :)

**Comment by clayrisser** [comment]
Yeah, I definitely agree. I added a better example. I really appreciate the feedback.

<img width="628" alt="Screen Shot 2019-08-29 at 10 51 23 AM" src="https://user-images.githubusercontent.com/6234038/63955947-314d0580-ca4b-11e9-94f4-8cf98465fbc9.png">

**Comment by clayrisser** [comment]
You can paste the example rendered code at [astexplorer.net](https://astexplorer.net) and you will see it matches the rendered AST.
